import type { Activity, Chat, Person } from './types';

export const activities: Activity[] = [
  {
    id: 'futbol-parque',
    title: 'Partidito de fútbol al atardecer',
    category: 'Fútbol',
    day: 'Hoy',
    date: 'Jue, 24 oct',
    time: '19:30',
    location: 'Parque Grande José Antonio Labordeta',
    neighborhood: 'Romareda',
    participants: 8,
    capacity: 12,
    host: 'Álvaro M.',
    hostInitials: 'AM',
    description: 'Fútbol sin presión, buen rollo y tercer tiempo opcional. Nivel medio.',
    tone: 'coral',
    featured: true,
  },
  {
    id: 'cine-verdi',
    title: 'Una peli y comentarla después',
    category: 'Cine',
    day: 'Mañana',
    date: 'Vie, 25 oct',
    time: '20:15',
    location: 'Cines Aragonia',
    neighborhood: 'Universidad',
    participants: 4,
    capacity: 8,
    host: 'Irene G.',
    hostInitials: 'IG',
    description: 'Vemos una de estreno y acabamos con algo para picar cerca.',
    tone: 'violet',
    featured: true,
  },
  {
    id: 'juegos-centro',
    title: 'Juegos de mesa para descubrir',
    category: 'Juegos',
    day: 'Mañana',
    date: 'Vie, 25 oct',
    time: '18:00',
    location: 'Café Botánico',
    neighborhood: 'Centro',
    participants: 5,
    capacity: 8,
    host: 'Marcos R.',
    hostInitials: 'MR',
    description: 'Partidas rápidas, desde Catan hasta juegos de cartas. No hace falta saber jugar.',
    tone: 'gold',
    featured: true,
  },
  {
    id: 'canas-magdalena',
    title: 'Cañas por la Magdalena',
    category: 'Cañas',
    day: 'Sáb, 26 oct',
    date: 'Sáb, 26 oct',
    time: '13:00',
    location: 'Plaza de San Bruno',
    neighborhood: 'La Magdalena',
    participants: 7,
    capacity: 10,
    host: 'Lucía P.',
    hostInitials: 'LP',
    description: 'Ruta corta de bares, vermú y conversación sin agenda.',
    tone: 'teal',
  },
  {
    id: 'senderismo-monasterio',
    title: 'Senderismo: Monasterio de Piedra',
    category: 'Senderismo',
    day: 'Dom, 27 oct',
    date: 'Dom, 27 oct',
    time: '08:00',
    location: 'Salida desde Delicias',
    neighborhood: 'Delicias',
    participants: 11,
    capacity: 16,
    host: 'Nico S.',
    hostInitials: 'NS',
    description: 'Excursión de día completo. Compartimos coche y llevamos picnic.',
    tone: 'sky',
  },
  {
    id: 'cocina-tapas',
    title: 'Taller casero de tapas',
    category: 'Cocina',
    day: 'Sáb, 26 oct',
    date: 'Sáb, 26 oct',
    time: '18:30',
    location: 'La Cocina Colectiva',
    neighborhood: 'Arrabal',
    participants: 6,
    capacity: 8,
    host: 'Celia V.',
    hostInitials: 'CV',
    description: 'Cocinamos tres tapas aragonesas y cenamos juntos al terminar.',
    tone: 'gold',
  },
  {
    id: 'foto-ribera',
    title: 'Paseo de fotos por la ribera',
    category: 'Creativo',
    day: 'Dom, 27 oct',
    date: 'Dom, 27 oct',
    time: '10:30',
    location: 'Puente de Piedra',
    neighborhood: 'Arrabal',
    participants: 4,
    capacity: 10,
    host: 'Tomás L.',
    hostInitials: 'TL',
    description: 'Una vuelta tranquila para mirar Zaragoza con otros ojos. Móvil o cámara.',
    tone: 'teal',
  },
];

export const people: Person[] = [
  {
    id: 'ines',
    name: 'Inés Navarro',
    initials: 'IN',
    age: 29,
    occupation: 'Diseñadora editorial',
    bio: 'Busco planes sencillos, gente curiosa y descubrir rincones nuevos de la ciudad.',
    interests: ['Cine', 'Cañas', 'Creativo'],
    compatibility: 92,
    active: 'Organiza una tarde de cine',
    color: 'coral',
  },
  {
    id: 'david',
    name: 'David Bueno',
    initials: 'DB',
    age: 32,
    occupation: 'Ingeniero de sonido',
    bio: 'Entre conciertos, montaña y cualquier sobremesa que se alargue.',
    interests: ['Senderismo', 'Cañas', 'Fútbol'],
    compatibility: 86,
    active: 'Se apunta a senderismo',
    color: 'teal',
  },
  {
    id: 'marta',
    name: 'Marta Cebrián',
    initials: 'MC',
    age: 27,
    occupation: 'Arquitecta',
    bio: 'Me gustan los juegos con reglas raras y las conversaciones que empiezan sin plan.',
    interests: ['Juegos', 'Cine', 'Cocina'],
    compatibility: 81,
    active: 'Busca un plan para hoy',
    color: 'gold',
  },
  {
    id: 'ruben',
    name: 'Rubén Vidal',
    initials: 'RV',
    age: 35,
    occupation: 'Profesor de historia',
    bio: 'Zaragozano recién vuelto. Siempre tengo una recomendación y ganas de caminar.',
    interests: ['Senderismo', 'Cine', 'Creativo'],
    compatibility: 76,
    active: 'Ha guardado una ruta',
    color: 'violet',
  },
];

export const chats: Chat[] = [
  {
    id: 'grupo-futbol',
    name: 'Fútbol al atardecer',
    initials: 'FA',
    preview: 'Álvaro: ¿llevamos petos claros?',
    time: '16:42',
    unread: 3,
    isGroup: true,
    activity: 'Hoy · 19:30',
    color: 'coral',
  },
  {
    id: 'ines-chat',
    name: 'Inés Navarro',
    initials: 'IN',
    preview: 'El cine de Aragonia tiene buena sesión',
    time: 'Ayer',
    color: 'teal',
  },
  {
    id: 'grupo-juegos',
    name: 'Juegos de mesa',
    initials: 'JM',
    preview: 'Marta: llevo un par de juegos nuevos',
    time: 'Ayer',
    unread: 1,
    isGroup: true,
    activity: 'Vie · 18:00',
    color: 'gold',
  },
  {
    id: 'david-chat',
    name: 'David Bueno',
    initials: 'DB',
    preview: '¿Te apetece la ruta del domingo?',
    time: 'Mar',
    color: 'violet',
  },
];